#!/usr/bin/env node
// Tact emits per-contract .ts wrappers under contracts/build/. They are pulled
// in by backend/commerce/escrow.ts via dynamic import and consequently end up
// in the backend tsc graph. Tact-generated code has many unused parameters
// (TS6133) which would fail backend `npm run typecheck` (noUnusedLocals:true).
//
// Rather than weaken backend tsconfig globally, we mark every emitted .ts
// file as `// @ts-nocheck` — they are autogenerated and treated as opaque.
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const buildDir = join(here, '..', 'build');

if (!existsSync(buildDir)) {
  console.warn(`[postprocessBuild] no build/ dir at ${buildDir} — nothing to do`);
  process.exit(0);
}

const HEADER = '// @ts-nocheck — autogenerated by Tact; see contracts/scripts/postprocessBuild.mjs';

let touched = 0;
for (const file of readdirSync(buildDir)) {
  if (!file.endsWith('.ts')) continue;
  const path = join(buildDir, file);
  const original = readFileSync(path, 'utf8');
  if (original.startsWith('// @ts-nocheck')) continue;
  writeFileSync(path, `${HEADER}\n${original}`);
  touched += 1;
}

console.log(`[postprocessBuild] ts-nocheck added to ${touched} file(s)`);
