/**
 * Escrow contract integration for the commerce backend (v4).
 *
 * v4 changes:
 * - Init signature расширен с 7 до 11 параметров
 * - amountNano split into sellerAmountNano + feeNano (fee поверх seller price)
 * - Добавлены collectionAddress, transferLimit, licenseContent для auto-mint
 *
 * Computes deterministic escrow addresses and builds TonConnect-ready payloads
 * from order parameters. Uses the Tact-generated wrapper at
 * contracts/build/Escrow_Escrow.ts.
 */

import { Address, beginCell, type Cell, type StateInit, contractAddress, toNano } from '@ton/core';
import { logger } from '../logger.js';

// Buffer для gas над amountNano — на случай PayEscrow attempts.
// Buyer платит amountNano + этот буфер; остаток возвращается в change tx.
const ESCROW_GAS_BUFFER = toNano('0.15');

// Default platform fee в basis points (15%).
// Используется при вычислении feeNano если caller передаёт только amountNano.
export const DEFAULT_PLATFORM_FEE_BPS = 1500;

let _cachedCode: Cell | null = null;
let _EscrowClass: EscrowStaticApi | null = null;

/**
 * Полная init signature Escrow v4 (11 параметров).
 */
interface EscrowStaticApi {
  init(
    orderId: bigint,
    buyer: Address,
    seller: Address,
    treasury: Address,
    amountNano: bigint,
    sellerAmountNano: bigint,
    feeNano: bigint,
    trialWindowSec: bigint,
    collectionAddress: Address,
    transferLimit: bigint,
    licenseContent: Cell,
  ): Promise<{ code: Cell; data: Cell }>;
}

async function loadEscrow(): Promise<EscrowStaticApi> {
  if (_EscrowClass) return _EscrowClass;
  // Dynamic import: typecheck не резолвит autogenerated .ts из contracts/build
  const modPath = '../../contracts/build/Escrow_Escrow.js';
  const mod = (await import(modPath)) as { Escrow: unknown };
  _EscrowClass = mod.Escrow as EscrowStaticApi;
  return _EscrowClass;
}

/**
 * Параметры ордера для вычисления Escrow-адреса.
 *
 * sellerAmountNano и feeNano — если оба не заданы, вычисляются из amountNano
 * и feeBps (default 1500 = 15%). Если заданы явно — используются as-is
 * (должен соблюдаться инвариант sellerAmount + fee == amount).
 */
export interface EscrowOrderParams {
  orderId: string;
  buyer: string;
  seller: string;
  treasury: string;
  amountNano: string;            // Total amount buyer pays
  sellerAmountNano?: string;     // Что получит seller
  feeNano?: string;              // Что получит treasury (platform fee)
  feeBps?: number;               // Если sellerAmount/fee не заданы — используется для расчёта
  trialWindowSec: number;
  collectionAddress: string;
  transferLimit?: number;        // 0 = soulbound (default), 1+ = transferable
  licenseContentUri: string;     // ipfs:// или https:// URI for NFT metadata
}

export interface EscrowComputeResult {
  escrowAddress: string;
  stateInitBase64: string;
  payloadBase64: string;
  totalAmountRaw: string;         // Что buyer должен заплатить (amount + gas buffer)
  sellerAmountNano: string;
  feeNano: string;
}

/**
 * Конвертация UUID-подобного orderId в 256-битное число для контракта.
 */
function orderIdToBigint(orderId: string): bigint {
  const hash = Buffer.from(orderId.replace(/-/g, '').padEnd(64, '0').slice(0, 64), 'hex');
  let n = 0n;
  for (let i = 0; i < 32; i++) {
    n = (n << 8n) | BigInt(hash[i]!);
  }
  return n;
}

/**
 * Строит Cell с URI для NFT metadata (TEP-64 off-chain content).
 * Format: [uint8 prefix 0x01] [snake-string URI].
 */
function buildLicenseContent(uri: string): Cell {
  return beginCell().storeUint(0x01, 8).storeStringTail(uri).endCell();
}

/**
 * Вычисляет split: seller_amount + fee == amount.
 * Если sellerAmount/fee заданы явно — проверяет инвариант.
 * Иначе считает из feeBps (basis points, 1500 = 15%).
 */
function resolveAmountSplit(params: EscrowOrderParams): { seller: bigint; fee: bigint; total: bigint } {
  const total = BigInt(params.amountNano);

  if (params.sellerAmountNano !== undefined && params.feeNano !== undefined) {
    const seller = BigInt(params.sellerAmountNano);
    const fee = BigInt(params.feeNano);
    if (seller + fee !== total) {
      throw new Error(
        `Amount split mismatch: sellerAmount(${seller}) + fee(${fee}) != amount(${total})`,
      );
    }
    return { seller, fee, total };
  }

  const feeBps = BigInt(params.feeBps ?? DEFAULT_PLATFORM_FEE_BPS);
  // fee = total * feeBps / 10000, остальное seller
  const fee = (total * feeBps) / 10000n;
  const seller = total - fee;
  return { seller, fee, total };
}

export async function computeEscrow(params: EscrowOrderParams): Promise<EscrowComputeResult> {
  const Escrow = await loadEscrow();

  const orderId = orderIdToBigint(params.orderId);
  const buyer = Address.parse(params.buyer);
  const seller = Address.parse(params.seller);
  const treasury = Address.parse(params.treasury);
  const collectionAddress = Address.parse(params.collectionAddress);
  const split = resolveAmountSplit(params);
  const licenseContent = buildLicenseContent(params.licenseContentUri);
  const transferLimit = BigInt(params.transferLimit ?? 0);

  const init = await Escrow.init(
    orderId,
    buyer,
    seller,
    treasury,
    split.total,
    split.seller,
    split.fee,
    BigInt(params.trialWindowSec),
    collectionAddress,
    transferLimit,
    licenseContent,
  );

  const stateInit: StateInit = { code: init.code, data: init.data };
  const escrowAddr = contractAddress(0, stateInit);

  const stateInitCell = beginCell()
    .storeBit(false)
    .storeBit(false)
    .storeBit(true)
    .storeRef(init.code)
    .storeBit(true)
    .storeRef(init.data)
    .storeBit(false)
    .endCell();

  const OP_PAY_ESCROW = 0xd2e5b971;
  const payloadCell = beginCell()
    .storeUint(OP_PAY_ESCROW, 32)
    .storeUint(0, 64)
    .endCell();

  const totalAmount = split.total + ESCROW_GAS_BUFFER;

  if (!_cachedCode) {
    _cachedCode = init.code;
    logger.info(`[escrow] code hash loaded: ${init.code.hash().toString('hex').slice(0, 16)}…`);
  }

  return {
    escrowAddress: escrowAddr.toString(),
    stateInitBase64: stateInitCell.toBoc().toString('base64'),
    payloadBase64: payloadCell.toBoc().toString('base64'),
    totalAmountRaw: totalAmount.toString(),
    sellerAmountNano: split.seller.toString(),
    feeNano: split.fee.toString(),
  };
}

export function buildConfirmDeliveryPayload(): string {
  const OP_CONFIRM = 0x45dfb5a1;
  const cell = beginCell().storeUint(OP_CONFIRM, 32).storeUint(0, 64).endCell();
  return cell.toBoc().toString('base64');
}

export function buildRefundIfNotMintedPayload(): string {
  const OP_REFUND_IF_NOT_MINTED = 0x5a8e1f23;
  const cell = beginCell().storeUint(OP_REFUND_IF_NOT_MINTED, 32).storeUint(0, 64).endCell();
  return cell.toBoc().toString('base64');
}

export function buildRegisterLicensePayload(licenseAddress: string): string {
  const OP_REGISTER_LICENSE = 0x70e30189;
  const addr = Address.parse(licenseAddress);
  const cell = beginCell()
    .storeUint(OP_REGISTER_LICENSE, 32)
    .storeAddress(addr)
    .endCell();
  return cell.toBoc().toString('base64');
}

/**
 * Payload для BuyerBurn — отправляется на адрес LicenseItem (не на escrow).
 * Triggers refund flow: item → escrow → buyer.
 */
export function buildBuyerBurnPayload(): string {
  const OP_BUYER_BURN = 0x7a1b3c5d;
  const cell = beginCell().storeUint(OP_BUYER_BURN, 32).storeUint(0, 64).endCell();
  return cell.toBoc().toString('base64');
}

/**
 * Payload для BurnLicense (admin/DMCA путь) — отправляется на Collection address
 * от имени ownerAddress. Collection форвардит Burn на конкретный item.
 */
export function buildBurnLicensePayload(itemAddress: string): string {
  const OP_BURN_LICENSE = 0x4d8e8a14;
  const addr = Address.parse(itemAddress);
  const cell = beginCell()
    .storeUint(OP_BURN_LICENSE, 32)
    .storeUint(0, 64)
    .storeAddress(addr)
    .endCell();
  return cell.toBoc().toString('base64');
}
