/**
 * Escrow contract integration for the commerce backend.
 *
 * Computes deterministic escrow addresses and builds TonConnect-ready
 * payloads from order parameters. Uses the Tact-generated wrapper
 * at contracts/build/Escrow_Escrow.ts.
 */

import { Address, beginCell, type Cell, type StateInit, contractAddress, toNano } from '@ton/core';
import { logger } from '../logger.js';
import { getTonClient } from '../tonforge/onchain/tonClient.js';
import {
  buildPayEscrowPayload,
  buildConfirmDeliveryPayload as buildConfirmDeliveryPayloadCell,
  buildRegisterLicensePayload as buildRegisterLicensePayloadCell,
} from '../tonforge/onchain/contractSchemas.js';

/**
 * Gas budgets paid by the buyer in a single payment transaction.
 * The buyer signs ONE TonConnect transaction for `price + GAS_TOTAL`.
 * Escrow keeps `ESCROW_GAS_BUFFER` for its own future operations
 * (refund / release). The remaining gas funds the oracle's
 * MintLicense + RegisterLicense transactions.
 */
const ESCROW_GAS_BUFFER = toNano('0.15');
const MINT_GAS_BUDGET = toNano('0.10');
const REGISTER_GAS_BUDGET = toNano('0.05');
const TOTAL_GAS_BUFFER = ESCROW_GAS_BUFFER + MINT_GAS_BUDGET + REGISTER_GAS_BUDGET;

export const GAS_BREAKDOWN = {
  escrowGasNano: ESCROW_GAS_BUFFER.toString(),
  mintGasNano: MINT_GAS_BUDGET.toString(),
  registerGasNano: REGISTER_GAS_BUDGET.toString(),
  totalGasNano: TOTAL_GAS_BUFFER.toString(),
} as const;

let _cachedCode: Cell | null = null;
let _EscrowClass: EscrowStaticApi | null = null;

interface EscrowStaticApi {
  init(
    orderId: bigint, buyer: Address, seller: Address, treasury: Address,
    amountNano: bigint, feeBps: bigint, trialWindowSec: bigint,
  ): Promise<{ code: Cell; data: Cell }>;
}

async function loadEscrow(): Promise<EscrowStaticApi> {
  if (_EscrowClass) return _EscrowClass;
  // Динамический путь — чтобы typecheck не резолвил autogenerated .ts из contracts/build
  const modPath = '../../contracts/build/Escrow_Escrow.js';
  const mod = (await import(modPath)) as { Escrow: unknown };
  _EscrowClass = mod.Escrow as EscrowStaticApi;
  return _EscrowClass;
}

export interface EscrowOrderParams {
  orderId: string;
  buyer: string;
  seller: string;
  treasury: string;
  amountNano: string;
  feeBps: number;
  trialWindowSec: number;
}

export interface EscrowComputeResult {
  escrowAddress: string;
  stateInitBase64: string;
  payloadBase64: string;
  totalAmountRaw: string;
}

function orderIdToBigint(orderId: string): bigint {
  const hash = Buffer.from(orderId.replace(/-/g, '').padEnd(64, '0').slice(0, 64), 'hex');
  let n = 0n;
  for (let i = 0; i < 32; i++) {
    n = (n << 8n) | BigInt(hash[i]!);
  }
  return n;
}

export async function computeEscrow(params: EscrowOrderParams): Promise<EscrowComputeResult> {
  const Escrow = await loadEscrow();
  const orderId = orderIdToBigint(params.orderId);
  const buyer = Address.parse(params.buyer);
  const seller = Address.parse(params.seller);
  const treasury = Address.parse(params.treasury);
  const amountNano = BigInt(params.amountNano);

  const init = await Escrow.init(
    orderId,
    buyer,
    seller,
    treasury,
    amountNano,
    BigInt(params.feeBps),
    BigInt(params.trialWindowSec),
  );

  const stateInit: StateInit = { code: init.code, data: init.data };
  const escrowAddr = contractAddress(0, stateInit);

  const stateInitCell = beginCell()
    .storeBit(false)
    .storeBit(false)
    .storeBit(true)
    .storeRef(init.code)
    .storeBit(true)
    .storeRef(init.data)
    .storeBit(false)
    .endCell();

  // PayEscrow opcode comes from contractSchemas.ts (canonical source).
  // Tact-generated TL-B: pay_escrow#cddea230 = PayEscrow.
  const payloadCell = buildPayEscrowPayload();

  const totalAmount = amountNano + TOTAL_GAS_BUFFER;

  if (!_cachedCode) {
    _cachedCode = init.code;
    logger.info(`[escrow] code hash loaded: ${init.code.hash().toString('hex').slice(0, 16)}…`);
  }

  return {
    escrowAddress: escrowAddr.toString(),
    stateInitBase64: stateInitCell.toBoc().toString('base64'),
    payloadBase64: payloadCell.toBoc().toString('base64'),
    totalAmountRaw: totalAmount.toString(),
  };
}

export function buildConfirmDeliveryPayload(): string {
  return buildConfirmDeliveryPayloadCell().toBoc().toString('base64');
}

export interface EscrowFundedCheck {
  ok: boolean;
  reason?: string;
  state?: number;
}

/**
 * Verify that the escrow contract at `escrowAddress` is in FUNDED state (1).
 *
 * The contract itself enforces `sender == buyer` and `value >= amountNano`
 * during PayEscrow, so once `state == 1` we know the payment came from the
 * intended buyer with sufficient amount. No additional TX scanning needed.
 *
 * Returns:
 *   ok=true             — escrow exists and is FUNDED (state == 1)
 *   ok=false ESCROW_NOT_FOUND  — contract not deployed yet (state != active and no balance)
 *   ok=false ESCROW_NOT_FUNDED — contract deployed but PayEscrow not received yet
 *   ok=false ESCROW_RELEASED   — already released to seller (state == 3)
 *   ok=false ESCROW_REFUNDED   — already refunded (state == 4)
 */
export async function verifyEscrowFunded(escrowAddress: string): Promise<EscrowFundedCheck> {
  try {
    const client = getTonClient();
    const addr = Address.parse(escrowAddress);
    const contractState = await client.getContractState(addr);

    if (contractState.state !== 'active') {
      return { ok: false, reason: 'ESCROW_NOT_FOUND' };
    }

    const result = await client.runMethod(addr, 'state');
    const state = Number(result.stack.readBigNumber());

    if (state === 1) return { ok: true, state };
    if (state === 0) return { ok: false, reason: 'ESCROW_NOT_FUNDED', state };
    if (state === 3) return { ok: false, reason: 'ESCROW_RELEASED', state };
    if (state === 4) return { ok: false, reason: 'ESCROW_REFUNDED', state };
    return { ok: false, reason: 'ESCROW_UNKNOWN_STATE', state };
  } catch (err) {
    logger.warn('[escrow.verify] runMethod failed:', err instanceof Error ? err.message : err);
    return { ok: false, reason: 'ESCROW_QUERY_FAILED' };
  }
}

export function buildRegisterLicensePayload(licenseAddress: string): string {
  const addr = Address.parse(licenseAddress);
  return buildRegisterLicensePayloadCell(addr).toBoc().toString('base64');
}
